### ISSUE TITLE
Error on require "Use of const in strict mode"

### ISSUE THREAD

**Issue by edshee** [hapijs/qs#131]
My app is throwing an error when trying to execute the line:
```
var Qs = require('qs);
```

Here is the error:

```
/home/ed/Documents/projectalchemy/node_modules/qs/lib/index.js:5
const Stringify = require('./stringify');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ed/Documents/projectalchemy/app.js:5:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by nlf** [comment]
the latest release of qs requires node 4.0.0 or greater. update your node and this error will go away.

**Comment by edshee** [comment]
Just figured this out myself and came here to close the issue only to see you'd already done it. Thanks

**Comment by tjconcept** [comment]
What is the recommendation for people using this module in browsers (e.g. via Browserify)? Even the latest Safari does not support `const` in strict mode.

**Comment by nlf** [comment]
use babel or something similar to transpile

**Comment by tjconcept** [comment]
Thanks. I'll stay on 5.x for now and add a transpiler if more modules follow suit.

**Comment by wayneashleyberry** [comment]
Just got hit by this issue as well... but Browserify's global transforms don't seem to do anything here :(

**Comment by gsdean** [comment]
@wayneashleyberry Same problem here, back to qs 5 until this gets sorts or browser support is better
