### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by Industrial** [hapijs/qs#133]
Hi.

It seems this module was recently updated to use the `const` keyword. I'm not sure why.

Why not compile to ES5 with Babel.js first and then export the ES5 so it works anywhere?

The error I'm getting:
```
[19:23:11] Development server has error.
/Users/tom/Code/Code9/test-loopback/node_modules/qs/lib/index.js:5
const Stringify = require('./stringify');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tom/Code/Code9/test-loopback/node_modules/request/lib/querystring.js:3:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by nlf** [comment]
because the primary usage of this module is inside hapi, which supports only node 4 or greater. this module has changed to follow suit. if you need an es5 compatible version, either stick to the 5.x releases or transpile it in your project.
