### ISSUE TITLE
Use of const in strict mode. - node 5.0.0

### ISSUE THREAD

**Issue by raistlinthewiz** [hapijs/qs#135]
I know that these previous reports exists: https://github.com/hapijs/qs/issues?utf8=%E2%9C%93&q=Use+of+const+in+strict+mode.

I'm using node 5.0.0 and still getting the error

```
 error: unhandled error SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/hypetrain/src/lib/api/giantbomb.js:11:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/hypetrain/src/controllers/frontend/game.js:14:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/home/ubuntu/hypetrain/src/routes/frontend.js:12:20)
    at new module.exports (/home/ubuntu/hypetrain/src/webServer.js:195:33)
    at /home/ubuntu/hypetrain/src/app.js:49:27
    at Promise._execute (/home/ubuntu/hypetrain/node_modules/bluebird/js/release/debuggability.js:142:9)
    at Promise._resolveFromExecutor (/home/ubuntu/hypetrain/node_modules/bluebird/js/release/promise.js:459:18)
    at new Promise (/home/ubuntu/hypetrain/node_modules/bluebird/js/release/promise.js:76:14)
    at /home/ubuntu/hypetrain/src/app.js:48:14
    at tryCatcher (/home/ubuntu/hypetrain/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/hypetrain/node_modules/bluebird/js/release/promise.js:488:31)
    at Promise._settlePromise (/home/ubuntu/hypetrain/node_modules/bluebird/js/release/promise.js:545:18)
    at Promise._settlePromise0 (/home/ubuntu/hypetrain/node_modules/bluebird/js/release/promise.js:590:10)
    at Promise._settlePromises (/home/ubuntu/hypetrain/node_modules/bluebird/js/release/promise.js:673:18)
    at Async._drainQueue (/home/ubuntu/hypetrain/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/home/ubuntu/hypetrain/node_modules/bluebird/js/release/async.js:135:10)
    at Async.drainQueues (/home/ubuntu/hypetrain/node_modules/bluebird/js/release/async.js:16:14)
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by Marsup** [comment]
Solved itself ?

**Comment by raistlinthewiz** [comment]
Nah, i was getting the issue on a circleci build system which uses 0.10 series node. Seems i need to replace qs.

**Comment by ahlee2326** [comment]
Any progress on this? @Marsup

**Comment by Marsup** [comment]
There's no progress to have, it's usually a developer error.
